"""platform core baseline

Revision ID: 20260713_0001
Revises:
Create Date: 2026-07-13 17:03:32.286203
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260713_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guest_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guest_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_guest_sessions_token_hash")),
        schema="app",
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("topic", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("publish_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discarded_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "NOT (published_at IS NOT NULL AND discarded_at IS NOT NULL)",
            name=op.f("ck_outbox_events_delivery_outcome"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint("topic", "aggregate_id", name="uq_outbox_events_topic_aggregate"),
        schema="app",
    )
    op.create_index(
        "ix_outbox_events_pending",
        "outbox_events",
        ["created_at"],
        unique=False,
        schema="app",
        postgresql_where=sa.text("published_at IS NULL AND discarded_at IS NULL"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="active", nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'disabled')", name=op.f("ck_users_account_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        schema="app",
    )
    op.create_table(
        "actors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("guest_session_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'human' AND NOT (owner_user_id IS NOT NULL AND "
            "guest_session_id IS NOT NULL)) OR (kind IN "
            "('model', 'agent', 'tool', 'system') AND owner_user_id IS NULL AND "
            "guest_session_id IS NULL)",
            name=op.f("ck_actors_ownership"),
        ),
        sa.CheckConstraint(
            "kind IN ('human', 'model', 'agent', 'tool', 'system')", name=op.f("ck_actors_kind")
        ),
        sa.ForeignKeyConstraint(
            ["guest_session_id"],
            ["app.guest_sessions.id"],
            name=op.f("fk_actors_guest_session_id_guest_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["app.users.id"],
            name=op.f("fk_actors_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actors")),
        sa.UniqueConstraint("key", name=op.f("uq_actors_key")),
        schema="app",
    )
    op.create_index(
        "uq_actors_guest_session_id",
        "actors",
        ["guest_session_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("guest_session_id IS NOT NULL"),
    )
    op.create_index(
        "uq_actors_owner_user_id",
        "actors",
        ["owner_user_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("owner_user_id IS NOT NULL"),
    )
    op.execute(
        sa.text(
            """
            INSERT INTO app.actors (id, kind, key, name)
            VALUES
                ('00000000-0000-4000-8000-000000000001', 'model', 'model:hina', 'Hina'),
                ('00000000-0000-4000-8000-000000000002', 'model', 'model:asuka-1', 'Asuka 1')
            """
        )
    )
    op.create_table(
        "auth_identities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("issuer", sa.String(length=512), nullable=False),
        sa.Column("subject", sa.String(length=512), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
            name=op.f("fk_auth_identities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_identities")),
        sa.UniqueConstraint("issuer", "subject", name="uq_auth_identities_issuer_subject"),
        schema="app",
    )
    op.create_index(
        op.f("ix_auth_identities_user_id"),
        "auth_identities",
        ["user_id"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "spaces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), server_default="personal", nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("guest_session_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'personal' AND ((owner_user_id IS NOT NULL) <> "
            "(guest_session_id IS NOT NULL))) OR (kind = 'shared' AND "
            "owner_user_id IS NULL AND guest_session_id IS NULL)",
            name=op.f("ck_spaces_ownership"),
        ),
        sa.CheckConstraint("kind IN ('personal', 'shared')", name=op.f("ck_spaces_kind")),
        sa.CheckConstraint("status IN ('active', 'archived')", name=op.f("ck_spaces_status")),
        sa.ForeignKeyConstraint(
            ["guest_session_id"],
            ["app.guest_sessions.id"],
            name=op.f("fk_spaces_guest_session_id_guest_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["app.users.id"],
            name=op.f("fk_spaces_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spaces")),
        schema="app",
    )
    op.create_index(
        "uq_spaces_guest_session_id",
        "spaces",
        ["guest_session_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("guest_session_id IS NOT NULL"),
    )
    op.create_index(
        "uq_spaces_owner_user_id",
        "spaces",
        ["owner_user_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("owner_user_id IS NOT NULL"),
    )
    op.create_table(
        "space_memberships",
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('owner', 'member')", name=op.f("ck_space_memberships_role")),
        sa.CheckConstraint(
            "status IN ('active', 'removed')", name=op.f("ck_space_memberships_status")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["app.actors.id"],
            name=op.f("fk_space_memberships_actor_id_actors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["app.spaces.id"],
            name=op.f("fk_space_memberships_space_id_spaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("space_id", "actor_id", name=op.f("pk_space_memberships")),
        schema="app",
    )
    op.create_table(
        "threads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("created_by_actor_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("default_answerer", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="active", nullable=False),
        sa.Column("revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_activity_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active', 'archived')", name=op.f("ck_threads_status")),
        sa.ForeignKeyConstraint(
            ["created_by_actor_id"],
            ["app.actors.id"],
            name=op.f("fk_threads_created_by_actor_id_actors"),
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["app.spaces.id"],
            name=op.f("fk_threads_space_id_spaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_threads")),
        schema="app",
    )
    op.create_index(
        op.f("ix_threads_last_activity_at"),
        "threads",
        ["last_activity_at"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_threads_space_id"), "threads", ["space_id"], unique=False, schema="app"
    )
    op.create_table(
        "thread_participants",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "role IN ('participant', 'answerer')", name=op.f("ck_thread_participants_role")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["app.actors.id"],
            name=op.f("fk_thread_participants_actor_id_actors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["app.threads.id"],
            name=op.f("fk_thread_participants_thread_id_threads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("thread_id", "actor_id", name=op.f("pk_thread_participants")),
        schema="app",
    )
    op.create_table(
        "thread_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("author_actor_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), server_default="message", nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('message')", name=op.f("ck_thread_entries_kind")),
        sa.ForeignKeyConstraint(
            ["thread_id", "author_actor_id"],
            ["app.thread_participants.thread_id", "app.thread_participants.actor_id"],
            name="fk_thread_entries_author_is_participant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["author_actor_id"],
            ["app.actors.id"],
            name=op.f("fk_thread_entries_author_actor_id_actors"),
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["app.threads.id"],
            name=op.f("fk_thread_entries_thread_id_threads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thread_entries")),
        sa.UniqueConstraint("thread_id", "id", name="uq_thread_entries_thread_id"),
        sa.UniqueConstraint(
            "thread_id",
            "id",
            "author_actor_id",
            name="uq_thread_entries_thread_id_author",
        ),
        sa.UniqueConstraint("thread_id", "ordinal", name="uq_thread_entries_thread_ordinal"),
        schema="app",
    )
    op.create_index(
        op.f("ix_thread_entries_thread_id"),
        "thread_entries",
        ["thread_id"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "entry_text_contents",
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "length(btrim(content)) > 0", name=op.f("ck_entry_text_contents_content_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["app.thread_entries.id"],
            name=op.f("fk_entry_text_contents_entry_id_thread_entries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("entry_id", name=op.f("pk_entry_text_contents")),
        schema="app",
    )
    op.execute(
        sa.text(
            """
            CREATE FUNCTION app.prevent_entry_mutation()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RAISE EXCEPTION 'thread entries are immutable';
            END;
            $$
            """
        )
    )
    op.execute(
        sa.text(
            """
            CREATE TRIGGER thread_entries_immutable
            BEFORE UPDATE ON app.thread_entries
            FOR EACH ROW EXECUTE FUNCTION app.prevent_entry_mutation()
            """
        )
    )
    op.execute(
        sa.text(
            """
            CREATE TRIGGER entry_text_contents_immutable
            BEFORE UPDATE ON app.entry_text_contents
            FOR EACH ROW EXECUTE FUNCTION app.prevent_entry_mutation()
            """
        )
    )
    op.execute(
        sa.text(
            """
            CREATE FUNCTION app.prevent_entry_delete_while_thread_exists()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM app.threads WHERE id = OLD.thread_id
                ) THEN
                    RAISE EXCEPTION 'thread entries are immutable';
                END IF;
                RETURN OLD;
            END;
            $$
            """
        )
    )
    op.execute(
        sa.text(
            """
            CREATE FUNCTION app.prevent_entry_text_delete_while_entry_exists()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM app.thread_entries WHERE id = OLD.entry_id
                ) THEN
                    RAISE EXCEPTION 'entry text is immutable';
                END IF;
                RETURN OLD;
            END;
            $$
            """
        )
    )
    op.execute(
        sa.text(
            """
            CREATE TRIGGER thread_entries_delete_guard
            AFTER DELETE ON app.thread_entries
            FOR EACH ROW EXECUTE FUNCTION app.prevent_entry_delete_while_thread_exists()
            """
        )
    )
    op.execute(
        sa.text(
            """
            CREATE TRIGGER entry_text_contents_delete_guard
            AFTER DELETE ON app.entry_text_contents
            FOR EACH ROW EXECUTE FUNCTION app.prevent_entry_text_delete_while_entry_exists()
            """
        )
    )
    op.create_table(
        "response_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("requester_actor_id", sa.UUID(), nullable=False),
        sa.Column("target_actor_id", sa.UUID(), nullable=False),
        sa.Column("input_entry_id", sa.UUID(), nullable=False),
        sa.Column("requested_answerer", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="queued", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'failed')",
            name=op.f("ck_response_requests_status"),
        ),
        sa.CheckConstraint(
            "(status = 'queued' AND started_at IS NULL AND finished_at IS NULL) OR "
            "(status = 'running' AND started_at IS NOT NULL AND finished_at IS NULL) OR "
            "(status IN ('completed', 'failed') AND finished_at IS NOT NULL)",
            name=op.f("ck_response_requests_state"),
        ),
        sa.ForeignKeyConstraint(
            ["thread_id", "target_actor_id"],
            ["app.thread_participants.thread_id", "app.thread_participants.actor_id"],
            name="fk_response_requests_target_is_participant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requester_actor_id"],
            ["app.actors.id"],
            name=op.f("fk_response_requests_requester_actor_id_actors"),
        ),
        sa.ForeignKeyConstraint(
            ["target_actor_id"],
            ["app.actors.id"],
            name=op.f("fk_response_requests_target_actor_id_actors"),
        ),
        sa.ForeignKeyConstraint(
            ["thread_id", "input_entry_id", "requester_actor_id"],
            [
                "app.thread_entries.thread_id",
                "app.thread_entries.id",
                "app.thread_entries.author_actor_id",
            ],
            name="fk_response_requests_input_entry_author",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["app.threads.id"],
            name=op.f("fk_response_requests_thread_id_threads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_response_requests")),
        sa.UniqueConstraint("id", "thread_id", name="uq_response_requests_id_thread"),
        sa.UniqueConstraint(
            "id",
            "thread_id",
            "target_actor_id",
            name="uq_response_requests_id_thread_target",
        ),
        schema="app",
    )
    op.create_index(
        op.f("ix_response_requests_thread_id"),
        "response_requests",
        ["thread_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "uq_response_requests_active_thread",
        "response_requests",
        ["thread_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_table(
        "executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("response_request_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("target_actor_id", sa.UUID(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), server_default="1", nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("execution_target", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="queued", nullable=False),
        sa.Column("partial_output", sa.Text(), server_default="", nullable=False),
        sa.Column("result_entry_id", sa.UUID(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("last_event_sequence", sa.Integer(), server_default="-1", nullable=False),
        sa.Column("last_event_id", sa.UUID(), nullable=True),
        sa.Column("last_event_type", sa.String(length=32), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("finish_reason", sa.String(length=32), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'queued' AND started_at IS NULL AND finished_at IS NULL "
            "AND result_entry_id IS NULL AND error_code IS NULL) OR "
            "(status = 'running' AND started_at IS NOT NULL AND finished_at IS NULL "
            "AND lease_expires_at IS NOT NULL AND result_entry_id IS NULL "
            "AND error_code IS NULL) OR "
            "(status = 'completed' AND started_at IS NOT NULL AND finished_at IS NOT NULL "
            "AND result_entry_id IS NOT NULL AND error_code IS NULL "
            "AND lease_expires_at IS NULL) OR "
            "(status = 'failed' AND finished_at IS NOT NULL AND result_entry_id IS NULL "
            "AND error_code IS NOT NULL AND lease_expires_at IS NULL)",
            name=op.f("ck_executions_state"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'failed')",
            name=op.f("ck_executions_status"),
        ),
        sa.ForeignKeyConstraint(
            ["response_request_id", "thread_id", "target_actor_id"],
            [
                "app.response_requests.id",
                "app.response_requests.thread_id",
                "app.response_requests.target_actor_id",
            ],
            name="fk_executions_request_target",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id", "result_entry_id", "target_actor_id"],
            [
                "app.thread_entries.thread_id",
                "app.thread_entries.id",
                "app.thread_entries.author_actor_id",
            ],
            name="fk_executions_result_entry_author",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executions")),
        sa.UniqueConstraint("attempt_id", name=op.f("uq_executions_attempt_id")),
        sa.UniqueConstraint(
            "response_request_id", "attempt_no", name="uq_executions_request_attempt"
        ),
        sa.UniqueConstraint("result_entry_id", name="uq_executions_result_entry_id"),
        schema="app",
    )
    op.create_index(
        op.f("ix_executions_response_request_id"),
        "executions",
        ["response_request_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_executions_status_lease_expires_at",
        "executions",
        ["status", "lease_expires_at"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "uq_executions_active_request",
        "executions",
        ["response_request_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_table(
        "response_context_items",
        sa.Column("response_request_id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["response_request_id", "thread_id"],
            ["app.response_requests.id", "app.response_requests.thread_id"],
            name="fk_response_context_items_request_same_thread",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id", "entry_id"],
            ["app.thread_entries.thread_id", "app.thread_entries.id"],
            name="fk_response_context_items_entry_same_thread",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "response_request_id", "entry_id", name=op.f("pk_response_context_items")
        ),
        sa.UniqueConstraint(
            "response_request_id", "ordinal", name="uq_response_context_items_request_ordinal"
        ),
        schema="app",
    )
    op.create_table(
        "model_executions",
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("requested_model", sa.String(length=64), nullable=False),
        sa.Column("resolved_model", sa.String(length=128), nullable=True),
        sa.Column("artifact_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["app.executions.id"],
            name=op.f("fk_model_executions_execution_id_executions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("execution_id", name=op.f("pk_model_executions")),
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_executions", schema="app")
    op.drop_table("response_context_items", schema="app")
    op.drop_index(
        "uq_executions_active_request",
        table_name="executions",
        schema="app",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index("ix_executions_status_lease_expires_at", table_name="executions", schema="app")
    op.drop_index(op.f("ix_executions_response_request_id"), table_name="executions", schema="app")
    op.drop_table("executions", schema="app")
    op.drop_index(
        "uq_response_requests_active_thread",
        table_name="response_requests",
        schema="app",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index(
        op.f("ix_response_requests_thread_id"), table_name="response_requests", schema="app"
    )
    op.drop_table("response_requests", schema="app")
    op.execute(sa.text("DROP TRIGGER entry_text_contents_delete_guard ON app.entry_text_contents"))
    op.execute(sa.text("DROP TRIGGER thread_entries_delete_guard ON app.thread_entries"))
    op.execute(sa.text("DROP FUNCTION app.prevent_entry_text_delete_while_entry_exists()"))
    op.execute(sa.text("DROP FUNCTION app.prevent_entry_delete_while_thread_exists()"))
    op.execute(sa.text("DROP TRIGGER entry_text_contents_immutable ON app.entry_text_contents"))
    op.execute(sa.text("DROP TRIGGER thread_entries_immutable ON app.thread_entries"))
    op.execute(sa.text("DROP FUNCTION app.prevent_entry_mutation()"))
    op.drop_table("entry_text_contents", schema="app")
    op.drop_index(op.f("ix_thread_entries_thread_id"), table_name="thread_entries", schema="app")
    op.drop_table("thread_entries", schema="app")
    op.drop_table("thread_participants", schema="app")
    op.drop_index(op.f("ix_threads_space_id"), table_name="threads", schema="app")
    op.drop_index(op.f("ix_threads_last_activity_at"), table_name="threads", schema="app")
    op.drop_table("threads", schema="app")
    op.drop_table("space_memberships", schema="app")
    op.drop_index(
        "uq_spaces_owner_user_id",
        table_name="spaces",
        schema="app",
        postgresql_where=sa.text("owner_user_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_spaces_guest_session_id",
        table_name="spaces",
        schema="app",
        postgresql_where=sa.text("guest_session_id IS NOT NULL"),
    )
    op.drop_table("spaces", schema="app")
    op.drop_index(op.f("ix_auth_identities_user_id"), table_name="auth_identities", schema="app")
    op.drop_table("auth_identities", schema="app")
    op.drop_index(
        "uq_actors_owner_user_id",
        table_name="actors",
        schema="app",
        postgresql_where=sa.text("owner_user_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_actors_guest_session_id",
        table_name="actors",
        schema="app",
        postgresql_where=sa.text("guest_session_id IS NOT NULL"),
    )
    op.drop_table("actors", schema="app")
    op.drop_table("users", schema="app")
    op.drop_index("ix_outbox_events_pending", table_name="outbox_events", schema="app")
    op.drop_table("outbox_events", schema="app")
    op.drop_table("guest_sessions", schema="app")
    # ### end Alembic commands ###
